model:
    arch: td4_psp ##
    backbone: resnet18 ##
    syncBN: False
    path_num: 4 ##

teacher: null

data:
    dataset: viper
    train_split: train
    val_split: val
    test_split: test
    img_rows: 1080
    img_cols: 1920
    path: data/viper

training:
    n_workers: 1
    train_iters: 40000
    batch_size: 4 ##
    val_interval: 500
    print_interval: 25
    loss:
        name: OhemCELoss2D
        thresh: 0.7
        ignore_index: 250
    optimizer:
        name: adaoptimizer
        momentum: 0.9
        wd: 1.0e-4
        lr0: 1.0e-2
        max_iter: 40000
        power: 0.9
        warmup_steps: 1000
        warmup_start_lr: 1.0e-5
    train_augmentations:
        colorjtr: [0.5,0.5,0.5]
        scale: [810,1440]
        rcrop: [256,512]
    resume: "" ##
    finetune: False
    visdom: False

validating:
    resume: "" ##
    n_workers: 1
    batch_size: 1
    val_augmentations:
        scale: [256,512]

